pipeline:
  build:
    image: ruby
    environment:
      - BUNDLE_PATH=/drone/.bundle
    commands:
      - bundle install
      - bundle exec jekyll build
    when:
      branch: [master]
      event: [push]
  deploy:
    image: drillster/drone-rsync
    hosts: [ "test.bortox.it" ]
    user: my_webapp
    source: _site
    target: /var/www/my_webapp/www
    recursive: true
    delete: true
    secrets: [ PLUGIN_KEY ]
#  notify:
#    image: drillster/drone-email
#    host: lafl-server.florian-latifi.at
#    port: 25
#    from: Drone <drone@lafl-server.florian-latifi.at>
#    when:
#      status: [ failure, success ]

branches: master